### ISSUE TITLE
Configurar Grafana

### ISSUE THREAD

**Issue by rogeriosouzax** [pedropagotto/tech-challenge-fiap-01#32]
● Configurar um dashboard em Grafana para visualizar as métricas
coletadas pelo Prometheus.
● Criar painéis para exibir métricas específicas como latência por endpoint,
contagem de requisições por status de resposta, uso de recursos do
sistema etc.

**Comment by pedropagotto** [comment]
1. Latência (Tempo de Resposta)
Métrica: request_duration_seconds
Objetivo: Acompanhar quanto tempo a API leva para responder a uma requisição. É fundamental para garantir que os usuários tenham uma experiência rápida.
Sugestão de visualização: Gráfico de linhas com percentis (p50, p95, p99) para medir latências médias e as maiores.
2. Taxa de Erros (Error Rate)
Métrica: http_errors_total
Objetivo: Monitorar o número de respostas de erro (códigos 4xx e 5xx). Essa métrica ajuda a identificar problemas que afetam os usuários.
Sugestão de visualização: Gráfico de barras empilhadas ou uma linha para exibir os diferentes tipos de erro HTTP.
3. Taxa de Sucesso (Success Rate)
Métrica: http_requests_total
Objetivo: Medir a proporção de requisições bem-sucedidas (códigos 2xx) versus o total de requisições. Essa métrica ajuda a manter o controle sobre a qualidade do serviço.
Sugestão de visualização: Medidor (gauge) ou gráfico de linha mostrando a porcentagem de requisições bem-sucedidas.
4. Número de Requisições (Request Rate)
Métrica: http_requests_total
Objetivo: Acompanhar o número total de requisições feitas à API em um determinado período de tempo.
Sugestão de visualização: Gráfico de linhas para observar a carga de trabalho e picos de tráfego.
5. Taxa de Requisições por Método HTTP
Métrica: http_requests_total{method}
Objetivo: Observar o volume de requisições categorizadas por método (GET, POST, PUT, DELETE) para entender o uso da API.
Sugestão de visualização: Gráfico de barras empilhadas ou gráfico de pizza para comparação entre métodos.
6. Taxa de Throttling/Limit Exceeded
Métrica: http_throttled_requests_total
Objetivo: Identificar quantas requisições estão sendo limitadas ou rejeitadas devido a políticas de controle de taxa (rate limiting).
Sugestão de visualização: Gráfico de barras mostrando a quantidade de requisições limitadas.
7. Utilização de Recursos (CPU e Memória)
Métrica: container_cpu_usage_seconds_total e container_memory_usage_bytes
Objetivo: Medir o consumo de CPU e memória dos containers que rodam a API.
Sugestão de visualização: Gráfico de linha ou gauge para monitoramento em tempo real dos recursos utilizados.
8. Métrica de Conexões Ativas
Métrica: active_connections
Objetivo: Monitorar o número de conexões ativas à API, o que ajuda a identificar gargalos ou sobrecarga.
Sugestão de visualização: Gráfico de linhas ou gauge para monitorar picos e quedas no número de conexões.
9. Tempo de Uptime (Disponibilidade)
Métrica: up
Objetivo: Garantir que a API esteja sempre disponível e monitorar seu tempo de atividade.
Sugestão de visualização: Gauge para indicar a disponibilidade em tempo real (1 para disponível, 0 para indisponível).
10. Taxa de Retries/Requisições Retransmitidas
Métrica: http_retries_total
Objetivo: Monitorar quantas requisições precisaram ser retransmitidas devido a falhas temporárias. Um número elevado pode indicar problemas de instabilidade.
Sugestão de visualização: Gráfico de linha mostrando o número de retries ao longo do tempo.
11. Uso de Cache (Hit/Miss Ratio)
Métrica: cache_hit_total, cache_miss_total
Objetivo: Acompanhar a eficiência do uso de cache na API e otimizar o desempenho.
Sugestão de visualização: Gráfico de barras ou linhas mostrando a relação entre acertos e falhas no cache.
12. Tamanho das Respostas
Métrica: response_size_bytes
Objetivo: Medir o tamanho médio das respostas da API. Tamanhos muito grandes podem indicar ineficiência ou a necessidade de otimizar o payload.
Sugestão de visualização: Gráfico de linha ou histogramas para visualizar a distribuição dos tamanhos das respostas.
13. Taxa de Timeout
Métrica: http_timeouts_total
Objetivo: Monitorar quantas requisições ultrapassaram o tempo limite (timeout), indicando possíveis problemas de latência ou sobrecarga.
Sugestão de visualização: Gráfico de linha ou barras mostrando o número de timeouts ao longo do tempo.
